[package]
version = "0.1.0"
name = "bid-server"
edition = "2021"


[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
cli-batteries = "0.5"
clap = { version = "4.5.4", features = ["derive"] }
rocket_cors = "0.6.0"

[build-dependencies]
cli-batteries = "0.5"
