[package]
version = "0.1.0"
name = "bid-server"
edition = "2021"


[dependencies]
rocket = "0.5.1"
cli-batteries = "0.5"
clap = { version = "4.5.4", features = ["derive"] }

[build-dependencies]
cli-batteries = "0.5"
