  name: Frontend Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  #  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  # Single deploy job since we're just deploying
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/
    permissions:
      contents: write
      pages: write
      deployments: write
      id-token: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: './frontend/yarn.lock'
      - run: corepack enable
      - run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zktripster
          directory: ./frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
